
/*
----------------------------------------------------------------
  TRIDENTCOM FILE LOADER
  Generated for Tridentlib
  Generated at 2019/08/11
----------------------------------------------------------------
*/

_tridentlib.defineAddon("Tridentlib", "tridentcom", "true")
_tridentlib.LoadFile("tridentlib/charts/line.lua", "Unknown", "server", 1)
_tridentlib.LoadFile("tridentlib/charts/bar.lua", "Unknown", "server", 1)
_tridentlib.LoadFile("tridentlib/charts/pie.lua", "Unknown", "server", 1)
_tridentlib.LoadFile("tridentlib/charts/scatter.lua", "Unknown", "server", 1)
_tridentlib.LoadFile("tridentlib/bgui/#bconnector.lua", "Connector", "client", 3)
_tridentlib.LoadFile("tridentlib/bgui/#bendpoint.lua", "Endpoint", "client", 3)
_tridentlib.LoadFile("tridentlib/bgui/#bresizablebox.lua", "Resizable Box", "client", 3)
_tridentlib.LoadFile("tridentlib/bgui/#bstarrater.lua", "Star rater", "client", 3)
_tridentlib.LoadFile("tridentlib/bgui/bblueprint.lua", "Blueprint", "client", 3)
_tridentlib.LoadFile("tridentlib/bgui/bbutton.lua", "Button", "client", 3)
_tridentlib.LoadFile("tridentlib/bgui/bcalender.lua", "Calender", "client", 3)
_tridentlib.LoadFile("tridentlib/bgui/bcheckbox.lua", "Checkbox", "client", 3)
_tridentlib.LoadFile("tridentlib/bgui/bdropdown.lua", "Dropdown", "client", 3)
_tridentlib.LoadFile("tridentlib/bgui/bframe.lua", "Frame", "client", 3)
_tridentlib.LoadFile("tridentlib/bgui/bitemlist.lua", "Itemlist", "client", 3)
_tridentlib.LoadFile("tridentlib/bgui/bnumslider.lua", "Num slider", "client", 3)
_tridentlib.LoadFile("tridentlib/bgui/bpassentry.lua", "Password Entry", "client", 3)
_tridentlib.LoadFile("tridentlib/bgui/bscrollbar.lua", "Scrollbar", "client", 3)
_tridentlib.LoadFile("tridentlib/bgui/btextentry.lua", "Text Entry", "client", 3)
_tridentlib.LoadFile("tridentlib/bgui/btitlecard.lua", "Title Card", "client", 3)
_tridentlib.LoadFile("tridentlib/bgui/btogglebox.lua", "Toggle Box", "client", 3)
_tridentlib.LoadFile("tridentlib/bgui/cl_tdlib.lua", "TDLIB", "client", 3)
_tridentlib.LoadFile("tridentlib/bgui/_functions.lua", "Functions", "client", 2)
_tridentlib.LoadFile("tridentlib/functions/base.lua", "Base Module", "shared", 1)
_tridentlib.LoadFile("tridentlib/functions/blueprint.lua", "Blueprint Lib", "client", 1)
_tridentlib.LoadFile("tridentlib/functions/byte.lua", "Byte Module", "shared", 1)
_tridentlib.LoadFile("tridentlib/functions/charts.lua", "Charts Module", "disabled", 1)
_tridentlib.LoadFile("tridentlib/functions/color.lua", "Color Module", "client", 1)
_tridentlib.LoadFile("tridentlib/functions/database.lua", "Database Module", "server", 10)
_tridentlib.LoadFile("tridentlib/functions/dataset.lua", "Dataset Module", "server", 1)
_tridentlib.LoadFile("tridentlib/functions/gmslib.lua", "GMS Module", "client", 1)
_tridentlib.LoadFile("tridentlib/functions/derma.lua", "Derma Module", "client", 1)
_tridentlib.LoadFile("tridentlib/functions/image.lua", "Image Module", "client", 1)
_tridentlib.LoadFile("tridentlib/functions/key.lua", "Keybind Module", "client", 1)
_tridentlib.LoadFile("tridentlib/functions/math.lua", "Math Module", "shared", 1)
_tridentlib.LoadFile("tridentlib/functions/meta.lua", "Meta Lib", "shared", 1)
_tridentlib.LoadFile("tridentlib/functions/net.lua", "Net Module", "shared", 1)
_tridentlib.LoadFile("tridentlib/functions/playermanager.lua", "PlayerManager Module", "shared", 1)
_tridentlib.LoadFile("tridentlib/functions/sha1.lua", "SHA Lib", "server", 1)
_tridentlib.LoadFile("tridentlib/functions/slowload.lua", "SlowLoad Module", "client", 1)
_tridentlib.LoadFile("tridentlib/functions/prems.lua", "Prems Module", "shared", 1)
_tridentlib.LoadFile("tridentlib/functions/socket.lua", "Websocket Module", "server", 1)
_tridentlib.LoadFile("tridentlib/functions/tests.lua", "Test Code", "shared", 1)
_tridentlib.LoadFile("tridentlib/functions/sound.lua", "Sound Module", "client", 1)
_tridentlib.LoadFile("tridentlib/-gredux/panel.lua", "Unknown", "server", 1)
_tridentlib.LoadFile("tridentlib/-gredux/exampleApp/app.lua", "Gredux ExampleApp", "client", 1)
_tridentlib.LoadFile("tridentlib/-gredux/exampleApp/app/index.lua", "Unknown", "server", 1)
_tridentlib.LoadFile("tridentlib/-gredux/exampleApp/app/components/displayData.lua", "COMPONENT || Display DATA.", "client", 1)
_tridentlib.LoadFile("tridentlib/-gredux/exampleApp/store/actions/getData.lua", "ACTION || Get data from server.", "client", 1)
_tridentlib.LoadFile("tridentlib/-gredux/exampleApp/store/reducers/getData.lua", "REDUCER || Get data from server.", "client", 1)